### ISSUE TITLE
Add discord icon in the footer section

### ISSUE THREAD

**Issue by sejalvasan** [SheGazette/SheGazetteWebsite#3]
Our social media handles are listed in the footer on the home page and our team page - add the discord icon there.

**Comment by pratham-arora** [comment]
Can I try this issue? This is the first time I am trying to contribute to open source.

**Comment by sejalvasan** [comment]
> Can I try this issue? This is the first time I am trying to contribute to open source.

>Sure, go ahead @pratham-arora

**Comment by pratham-arora** [comment]
I have made a pull request
